// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCg9eChspgetUoFsNZOlwW3wBRMcP1jVZY',
    appId: '1:728238090742:web:97b47ccaf85a21483affd7',
    messagingSenderId: '728238090742',
    projectId: 'itsolution-93657',
    authDomain: 'itsolution-93657.firebaseapp.com',
    storageBucket: 'itsolution-93657.firebasestorage.app',
    measurementId: 'G-ZN52N8K1G2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpE8YKiJlSyUHI0KBCQOGS2PajVjJbsxk',
    appId: '1:728238090742:android:3f0f24b50f9ef6953affd7',
    messagingSenderId: '728238090742',
    projectId: 'itsolution-93657',
    storageBucket: 'itsolution-93657.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaiiVybucvU4uuR1s-2Az450Xt3JE4S-U',
    appId: '1:728238090742:ios:ef4c72ee305d4f983affd7',
    messagingSenderId: '728238090742',
    projectId: 'itsolution-93657',
    storageBucket: 'itsolution-93657.firebasestorage.app',
    iosBundleId: 'com.example.itapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaiiVybucvU4uuR1s-2Az450Xt3JE4S-U',
    appId: '1:728238090742:ios:ef4c72ee305d4f983affd7',
    messagingSenderId: '728238090742',
    projectId: 'itsolution-93657',
    storageBucket: 'itsolution-93657.firebasestorage.app',
    iosBundleId: 'com.example.itapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCg9eChspgetUoFsNZOlwW3wBRMcP1jVZY',
    appId: '1:728238090742:web:b384aeaefff9ae5e3affd7',
    messagingSenderId: '728238090742',
    projectId: 'itsolution-93657',
    authDomain: 'itsolution-93657.firebaseapp.com',
    storageBucket: 'itsolution-93657.firebasestorage.app',
    measurementId: 'G-TMCH2HCFXZ',
  );
}
